GET http://localhost:3001/api/persons/

###
GET http://localhost:3001/api/persons/66b3a4fc24d23216e9845a77

###
GET http://localhost:3001/api/persons/50084

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "kostas P",
    "number": "6962536422"
}

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Petros K",
    "number": "75767676356"
}

###
PUT http://localhost:3001/api/persons/66b3e28e5230678d18c5f79f HTTP/1.1
content-type: application/json

{
    "name": "Allo onoma",
    "number": "75767676356"
}

###
DELETE http://localhost:3001/api/persons/66b3d7cac54c620a85217dec

###
HEAD http://localhost:3001/api/persons/